name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t spotifyflaccer:0.0.1 --no-cache .

    - name: Run tests in Docker container
      run: docker run spotifyflaccer:0.0.1 